### ISSUE TITLE
request: option to only allow it to be used by OPs

### ISSUE THREAD

**Issue by peow** [Tee-6/Cat_Eyes#1]
if you accept this suggestion, please update to 1.20.1

and I don't know if this is on purpose, but when you activate Cat Eyes and close your world and open another, the effect remains, you have to deactivate it to return to normal

**Comment by Tee-6** [comment]
This is not a server mod, so there's no way to restrict permissions based on server roles. It's a client mod. Only players who have installed it can use it.
