### ISSUE TITLE
Update the GitHub repository 1.21

### ISSUE THREAD

**Issue by Grinhecker** [Tee-6/Cat_Eyes#2]
I am trying to add this motto a Modrinth modpack, but in order to add it, I need the download URL to be on of these:
cdn.modrinth.com
github.com
raw.githubusercontent.com
gitlab.com

I would appreciate it if You uploaded the latest version to GitHub

**Comment by Grinhecker** [comment]
Until the release is published, I created a fork of this repository. https://github.com/grinheckerdev/Cat_Eyes_1.21_UNOFFICIAL

**Comment by Tee-6** [comment]
@Grinhecker 
Moving forward, all version updates will have a GitHub Release, starting with 1.21.1. Thanks for providing 1.21 for the community via the fork.
Sorry I didn't do it before; I just now learned how to do Tags and Releases

**Comment by Grinhecker** [comment]
Thanks a ton!
